# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d8BJ08fAXr2yIFnP9lPoNON77c9IQteW
"""

print("hellooo")